Update functions.php
Update to address 
Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in
/wp-content/plugins/onelogin-saml-sso/php/functions.php